Repository terasolunaorg/guideline, pull requests merged in 2018-03, with the labels that each got.

#3294 Modified Description about RedirectAttributes #3293
  source/ImplementationAtEachLayer/ApplicationLayer.rst
Labels: 5.5.0, improvement

#3276 fix description of where SPRING_SECURITY_LAST_EXCEPTION is stored #2994
  source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst
  source/Introduction/ChangeLog.rst
  source/Security/Authentication.rst
  source/Tutorial/TutorialSecurity.rst
Labels: 5.5.0, clerical error

#3316 change TodoServiceImpl#findOne method private to public at REST tutorial #3303
  source/Tutorial/TutorialREST.rst
  source/Tutorial/TutorialTodo.rst
Labels: 5.5.0, improvement

#3317 Delete warning-statement that has already been fixed #3263
  source/Introduction/ChangeLog.rst
  source/Security/OAuth.rst
Labels: 5.5.0

#3319 [5.4.x]Delete warning-statement that has already been fixed #3263
  source/Introduction/ChangeLog.rst
  source/Security/OAuth.rst
Labels: 5.4.2

#3320 [5.4.1.RELEASE]Delete warning-statement that has already been fixed #3263
  source/Introduction/ChangeLog.rst
  source/Security/OAuth.rst
Labels: 5.4.1

#3306 [5.3.x] move login.jsp from webapp to webapp web inf views 5.3.x #3260
  source/Tutorial/TutorialSecurity.rst
  source/Tutorial/images_Security/security_tutorial-application-layer-package-explorer.png
Labels: 5.3.3

#3307 [5.2.x] move login.jsp from webapp to webapp web inf views 5.2.x #3260
  source/Tutorial/TutorialSecurity.rst
  source/Tutorial/images_Security/security_tutorial-application-layer-package-explorer.png
Labels: 5.2.2

#3308 [5.1.x] move login.jsp from webapp to webapp web inf views 5.1.x #3260
  source/Security/Tutorial.rst
  source/Security/images_Tutorial/security_tutorial-application-layer-package-explorer.png
Labels: 5.1.2

#3309 [5.0.x] move login.jsp from webapp to webapp web inf views 5.0.x #3260
  source/Security/Tutorial.rst
  source/Security/images_Tutorial/security_tutorial-application-layer-package-explorer.png
Labels: 5.0.3

#3310 [1.0.x] move login.jsp from webapp to webapp web inf views 1.0.x #3260
  source/Security/Tutorial.rst
  source/Security/images_Tutorial/security_tutorial-application-layer-package-explorer.png
Labels: 1.0.7

#3312 [5.4.x] Unification of naming convention of groupId in Tutorial chapter #3219
  source/Security/SecureLoginDemo.rst
  source/Tutorial/TutorialREST.rst
  source/Tutorial/TutorialTodo.rst
  source/Tutorial/images/NewMVCProjectCreate.png
  source/Tutorial/images/NewMVCProjectImport.png
  source/Tutorial/images/create-mapper-for-mybatis3.png
  source/Tutorial/images/image004.png
  source/Tutorial/images/image057.png
  source/Tutorial/images/image058.png
  source/Tutorial/images/image061.png
  source/Tutorial/images/image062.png
  source/Tutorial/images/image063.png
  source/Tutorial/images/image064.png
  source/Tutorial/images/image065.png
  source/Tutorial/images/image066.png
  source/Tutorial/images/presentation-hierarchical-view.png
  source/Tutorial/images_rest/exception-apierror.png
  source/Tutorial/images_rest/exception-handlingclass.png
  source/Tutorial/images_rest/exception-package.png
  source/Tutorial/images_rest/make-package-for-rest.png
Labels: 5.4.2, improvement, task

#3313 [5.4.x] modifi description of add logout button image in tutorial security.rst 5.4.x #3256
  source/Tutorial/TutorialSecurity.rst
Labels: 5.4.2

#3318 [5.4.x]Modified Description about RedirectAttributes #3293
  source/ImplementationAtEachLayer/ApplicationLayer.rst
Labels: 5.4.2

#3311 Add description of fetched data display into pagination overview #3218
  source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst
  source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst
  source/ArchitectureInDetail/WebApplicationDetail/images/pagination-overview_screen.png
  source/ArchitectureInDetail/WebApplicationDetail/images_Pagination/materialPagination.pptx
  source/Introduction/ChangeLog.rst
Labels: 5.5.0

#3325 [5.4.x]Session Tutorial Application is not implemented for tiles #3270
  source/Introduction/ChangeLog.rst
  source/Tutorial/TutorialSession.rst
Labels: 5.4.2

#3330 [5.4.x]modified input tag of code block(attributes) #3186
  source/Security/OAuth.rst
Labels: 5.4.2

#3289 [5.4.x] fix description spsring security last exception 5.4.x #2994
  source/ArchitectureInDetail/WebApplicationDetail/MessageManagement.rst
  source/Introduction/ChangeLog.rst
  source/Security/Authentication.rst
  source/Tutorial/TutorialSecurity.rst
Labels: 5.4.1, clerical error

#3254 Delete defines View Resolver with bean element #3197
  source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
  source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst
  source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst
  source/ImplementationAtEachLayer/ApplicationLayer.rst
  source/Introduction/ChangeLog.rst
  source/Overview/FirstApplication.rst
  source/Tutorial/TutorialTodo.rst
Labels: 5.5.0, improvement

#3255 add codelist direct reference from jsp #3246
  source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst
  source/Introduction/ChangeLog.rst
Labels: 5.5.0, improvement

#3334 [5.4.x]Delete defines View Resolver with bean element #3197
  source/ArchitectureInDetail/WebApplicationDetail/ExceptionHandling.rst
  source/ArchitectureInDetail/WebApplicationDetail/FileDownload.rst
  source/ArchitectureInDetail/WebApplicationDetail/TilesLayout.rst
  source/ImplementationAtEachLayer/ApplicationLayer.rst
  source/Introduction/ChangeLog.rst
  source/Overview/FirstApplication.rst
  source/Tutorial/TutorialTodo.rst
Labels: 5.4.2

#3321 [5.4.x] Add description of fetched data display into pagination overview #3218
  source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst
  source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst
  source/ArchitectureInDetail/WebApplicationDetail/images/pagination-overview_screen.png
  source/ArchitectureInDetail/WebApplicationDetail/images_Pagination/materialPagination.pptx
  source/Introduction/ChangeLog.rst
Labels: 5.4.2

#3335 Correct error in description of package hierarchy #3219
  source/Tutorial/TutorialREST.rst
Labels: 5.5.0, clerical error

#3333 [5.4.x] codelist been direct reference from jsp by sp el expression 5.4.x #3246
  source/ArchitectureInDetail/WebApplicationDetail/Codelist.rst
  source/Introduction/ChangeLog.rst
Labels: 5.4.2

#3341 [5.4.x] fix change log about codelist bean definision #3329
  source/Introduction/ChangeLog.rst
Labels: 5.4.2
