Repository terasolunaorg/guideline, pull requests merged in 2018-02, with the labels that each got.

#3261 Move login.jsp from just below webapp to webapp/WEB-INF/views/login in TutorialSecurity.rst #3260
  source/Tutorial/TutorialSecurity.rst
  source/Tutorial/images_Security/security_tutorial-application-layer-package-explorer.png
Labels: 5.5.0

#3272 Reflect blank project change to png files in TutorialRest #3271
  source/Tutorial/images_rest/add-spring-mvc-rest.png
  source/Tutorial/images_rest/application-messages.png
  source/Tutorial/images_rest/validation-messages.png
Labels: 5.5.0, clerical error, next milestone

#3278 Different contents of spring-mvc.xml in TutorialSecurity.rst #3275
  source/Tutorial/TutorialSecurity.rst
Labels: 5.5.0, clerical error

#3285 Change file creation method from copy to create #3283
  source/Introduction/ChangeLog.rst
  source/Tutorial/TutorialREST.rst
Labels: 5.5.0, next milestone

#3286 [5.4.x] Move the description of cssStyle to the CSS file #3232
  source/Tutorial/TutorialTodo.rst
Labels: 5.4.1, improvement

#3279 [5.4.x] Different contents of spring-mvc.xml in TutorialSecurity.rst #3275
  source/Tutorial/TutorialSecurity.rst
Labels: 5.4.1

#3291 [5.4.x] move login.jsp from webapp to webapp web inf views#3260
  source/Tutorial/TutorialSecurity.rst
  source/Tutorial/images_Security/security_tutorial-application-layer-package-explorer.png
Labels: 5.4.1

#3295 [5.4.x] Move Create Todo button creation description #3233
  source/Introduction/ChangeLog.rst
  source/Tutorial/TutorialTodo.rst
  source/Tutorial/images/image067.png
  source/Tutorial/images/show-all-todo-note.png
Labels: 5.4.1

#3296 [5.4.x] Reflect blank project change to png files in TutorialRest #3271
  source/Tutorial/images_rest/add-spring-mvc-rest.png
  source/Tutorial/images_rest/application-messages.png
  source/Tutorial/images_rest/validation-messages.png
Labels: 5.4.1, clerical error

#3297 The TOC in TagLibAndELFunctions.rst has disappeared. #3172
  source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst
Labels: 5.5.0, bug

#3299 unified terms #3147
  source/ArchitectureInDetail/GeneralFuncDetail/Logging.rst
  source/ArchitectureInDetail/WebApplicationDetail/Pagination.rst
  source/ArchitectureInDetail/WebApplicationDetail/SessionManagement.rst
  source/ArchitectureInDetail/WebServiceDetail/SOAP.rst
  source/ImplementationAtEachLayer/ApplicationLayer.rst
  source/Introduction/ChangeLog.rst
  source/Overview/ApplicationLayering.rst
  source/Overview/FirstApplication.rst
  source/Security/SpringSecurity.rst
  source/Tutorial/TutorialREST.rst
Labels: 5.5.0

#3298 [5.4.x] The TOC in TagLibAndELFunctions.rst has disappeared. #3172
  source/ArchitectureInDetail/WebApplicationDetail/TagLibAndELFunctions.rst
Labels: 5.4.2

#3257 Modifi description of "add logout button" image in TutorialSecurity.rst #3256
  source/Tutorial/TutorialSecurity.rst
Labels: 5.5.0, clerical error
